### ISSUE TITLE
While loop runs forever

### ISSUE THREAD

**Issue by hoangkt57** [knaeckeKami/diffutil.dart#18]
int i = 0;

    while (i < postponedUpdates.length) {
      final update = postponedUpdates.elementAt(i);
      if (update.posInOwnerList == posInList && update.removal == removal) {
        postponedUpdate = update;
        postponedUpdates.removeAt(i);
        break;
      }
      i++;
    }
    while (i < postponedUpdates.length) {
      // re-offset all others
      final update = postponedUpdates.elementAt(i);
      if (removal) {
        update.currentPos--;
      } else {
        update.currentPos++;
      }
    }
    return postponedUpdate;
  
I encountered a case where the while loop ran forever if i = 2 and postponedUpdates.length = 3. 
I think you miss  i++;

**Comment by knaeckeKami** [comment]
You are correct!

Do you by any chance have a concrete case where this happens so I can add a regression test?

**Comment by knaeckeKami** [comment]
any update @hoangkt57  ?
