### ISSUE TITLE
Option for computing in an isolate

### ISSUE THREAD

**Issue by sagnik-sanyal** [knaeckeKami/diffutil.dart#23]
How to perform intensive calculations for diff util in an isolate ? @knaeckeKami

**Comment by knaeckeKami** [comment]
Use Isolate.run

**Comment by sagnik-sanyal** [comment]
The problem with this approach is it is throwing error cant send from SendPort.send, do you have any sample where you use isolate for calculating list diff using isolate ?                                                                                                                             

Here's the error : Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)

**Comment by knaeckeKami** [comment]
you can't use Isolates if you have Futures, Streams, FileHandles, etc. in your List.
